### ISSUE TITLE
fails in nixpkgs

### ISSUE THREAD

**Issue by domenkozar** [OceanSprint/tesh#57]
❯ /nix/store/yxi6i1phjad0kajm0s8zfykpbh832v5a-python3.12-tesh-0.3.2/bin/tesh --help
Traceback (most recent call last):
  File "/nix/store/yxi6i1phjad0kajm0s8zfykpbh832v5a-python3.12-tesh-0.3.2/bin/.tesh-wrapped", line 6, in <module>
    from tesh import tesh
  File "/nix/store/yxi6i1phjad0kajm0s8zfykpbh832v5a-python3.12-tesh-0.3.2/lib/python3.12/site-packages/tesh/__init__.py", line 5, in <module>
    from tesh.extract import extract
  File "/nix/store/yxi6i1phjad0kajm0s8zfykpbh832v5a-python3.12-tesh-0.3.2/lib/python3.12/site-packages/tesh/extract.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils'

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/357625
